import { X, Download, FileText, Sparkles, TrendingUp, AlertTriangle, Loader2 } from 'lucide-react';
import { useState } from 'react';
import jsPDF from 'jspdf';

interface Props {
  type: 'raw' | 'ai';
  onClose: () => void;
  zoneName?: string;
  crop?: string;
}

// ─── PDF Generation ─────────────────────────────────────────────────────────────

function generatePDF(
  type: 'raw' | 'ai',
  zoneName: string,
  crop: string,
  today: string
) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = 210;
  const pageH = 297;
  const margin = 18;
  const contentW = pageW - margin * 2;
  const footerH = 14;
  let y = 0;

  // ── Helpers ──────────────────────────────────────────────
  const hex = (h: string) => {
    const r = parseInt(h.slice(1, 3), 16);
    const g = parseInt(h.slice(3, 5), 16);
    const b = parseInt(h.slice(5, 7), 16);
    return { r, g, b };
  };
  const setColor = (h: string) => {
    const c = hex(h);
    doc.setTextColor(c.r, c.g, c.b);
  };
  const setFill = (h: string) => {
    const c = hex(h);
    doc.setFillColor(c.r, c.g, c.b);
  };
  const setStroke = (h: string) => {
    const c = hex(h);
    doc.setDrawColor(c.r, c.g, c.b);
  };

  // ── Page Header Helper ───────────────────────────────────
  const addHeader = () => {
    setFill('#16a34a');
    doc.rect(0, 0, pageW, 20, 'F');
    setColor('#ffffff');
    doc.setFontSize(14);
    doc.text('GreenStack', margin, 13);
    doc.setFontSize(9);
    doc.text('Vertical Farming Management System', pageW - margin, 13, { align: 'right' });
  };

  // ── Footer Helper ────────────────────────────────────────
  const addFooter = () => {
    setFill('#F9FAFB');
    doc.rect(0, pageH - footerH, pageW, footerH, 'F');
    setColor('#9CA3AF');
    doc.setFontSize(7.5);
    doc.text('Generated by GreenStack · Vertical Farming Management System', margin, pageH - 5);
    doc.text(`${today}`, pageW - margin, pageH - 5, { align: 'right' });
  };

  // ── Check if new page needed ─────────────────────────────
  const checkPageBreak = (requiredSpace: number) => {
    if (y + requiredSpace + footerH + 5 > pageH - footerH) {
      addFooter();
      doc.addPage();
      addHeader();
      y = 28; // Reset to just below header
      return true;
    }
    return false;
  };

  // ── Header bar ───────────────────────────────────────────
  addHeader();
  y = 28;

  // ── Report title ─────────────────────────────────────────
  setColor('#111827');
  doc.setFontSize(18);
  doc.text(type === 'ai' ? 'AI Analyzed Report' : 'Raw Data Report', margin, y);
  y += 10;

  // ── Meta row ─────────────────────────────────────────────
  setFill('#F3F4F6');
  setStroke('#E5E7EB');
  doc.roundedRect(margin, y, contentW, 22, 3, 3, 'FD');
  setColor('#6B7280');
  doc.setFontSize(8);
  doc.text('Generated', margin + 4, y + 7);
  doc.text('Zone', margin + 60, y + 7);
  doc.text('Crop', margin + 120, y + 7);
  setColor('#111827');
  doc.setFontSize(10);
  doc.text(today, margin + 4, y + 16);
  doc.text(zoneName, margin + 60, y + 16);
  doc.text(crop, margin + 120, y + 16);
  y += 30;

  if (type === 'raw') {
    // ── Section: Sensor Readings ──────────────────────────
    setColor('#16a34a');
    doc.setFontSize(11);
    doc.text('SENSOR READINGS (LAST 24H)', margin, y);
    y += 6;
    setStroke('#E5E7EB');
    doc.line(margin, y, pageW - margin, y);
    y += 6;

    // Table header
    setFill('#F9FAFB');
    doc.rect(margin, y, contentW, 8, 'F');
    setColor('#6B7280');
    doc.setFontSize(8);
    const cols = [margin + 2, margin + 55, margin + 95, margin + 135];
    doc.text('Sensor', cols[0], y + 5.5);
    doc.text('Min', cols[1], y + 5.5);
    doc.text('Max', cols[2], y + 5.5);
    doc.text('Avg', cols[3], y + 5.5);
    y += 8;

    const rows = [
      ['Soil Moisture', '58%', '68%', '62%'],
      ['Soil pH', '6.0', '6.4', '6.2'],
      ['Nutrient Level', '42 ppm', '58 ppm', '50 ppm'],
      ['Soil Temperature', '22°C', '26°C', '24°C'],
    ];
    rows.forEach((row, i) => {
      setFill(i % 2 === 0 ? '#FFFFFF' : '#F9FAFB');
      doc.rect(margin, y, contentW, 8, 'F');
      setStroke('#E5E7EB');
      doc.line(margin, y + 8, pageW - margin, y + 8);
      setColor('#111827');
      doc.setFontSize(9);
      doc.text(row[0], cols[0], y + 5.5);
      setColor('#6B7280');
      doc.text(row[1], cols[1], y + 5.5);
      doc.text(row[2], cols[2], y + 5.5);
      setColor('#111827');
      doc.text(row[3], cols[3], y + 5.5);
      y += 8;
    });
    y += 10;

    // ── Section: Hardware Activity Log ───────────────────
    setColor('#16a34a');
    doc.setFontSize(11);
    doc.text('HARDWARE ACTIVITY LOG', margin, y);
    y += 6;
    setStroke('#E5E7EB');
    doc.line(margin, y, pageW - margin, y);
    y += 8;

    const log = [
      ['06:00', 'Water pump ON for 12 min'],
      ['09:00', 'LED lights ON (auto-schedule)'],
      ['14:30', 'Cooling fan triggered · 18 min'],
      ['18:00', 'Fertilizer dispensed · 5 mL'],
      ['21:00', 'LED lights OFF'],
    ];
    log.forEach(([time, event]) => {
      setFill('#F0FDF4');
      setStroke('#DCFCE7');
      doc.roundedRect(margin, y - 1, contentW, 8, 2, 2, 'FD');
      setColor('#16a34a');
      doc.setFontSize(9);
      doc.text(time, margin + 3, y + 4.5);
      setColor('#374151');
      doc.text(event, margin + 22, y + 4.5);
      y += 10;
    });

  } else {
    // ── Section: Health Score ─────────────────────────────
    setFill('#F0FDF4');
    setStroke('#DCFCE7');
    doc.roundedRect(margin, y, contentW, 28, 3, 3, 'FD');
    setColor('#16a34a');
    doc.setFontSize(11);
    doc.text('CROP HEALTH SCORE', margin + 4, y + 9);
    doc.setFontSize(24);
    doc.text('82 / 100', margin + 4, y + 22);
    setColor('#6B7280');
    doc.setFontSize(8);
    doc.text('+6 vs last week · Trending positive', margin + 70, y + 22);
    y += 36;

    // ── Section: Comparative Analysis ────────────────────
    setColor('#16a34a');
    doc.setFontSize(11);
    doc.text('COMPARATIVE ANALYSIS', margin, y);
    y += 6;
    setStroke('#E5E7EB');
    doc.line(margin, y, pageW - margin, y);
    y += 8;

    const bars = [
      { label: 'Moisture', current: 62, required: 70 },
      { label: 'pH', current: 62, required: 65 },
      { label: 'Nutrient', current: 50, required: 80 },
      { label: 'Temperature', current: 24, required: 25 },
    ];
    const barW = contentW - 40;
    bars.forEach(({ label, current, required }) => {
      setColor('#374151');
      doc.setFontSize(9);
      doc.text(label, margin, y + 4);
      // Track
      setFill('#E5E7EB');
      doc.roundedRect(margin + 32, y, barW, 6, 1, 1, 'F');
      // Required fill (lighter)
      setFill('#86EFAC');
      doc.roundedRect(margin + 32, y, barW * (required / 100), 6, 1, 1, 'F');
      // Current fill (solid)
      setFill('#16a34a');
      doc.roundedRect(margin + 32, y, barW * (current / 100), 6, 1, 1, 'F');
      // Label
      setColor('#6B7280');
      doc.setFontSize(8);
      doc.text(`${current} / ${required}`, margin + 32 + barW + 2, y + 4.5);
      y += 12;
    });
    y += 4;

    // ── Section: AI Insights ─────────────────────────────
    setColor('#16a34a');
    doc.setFontSize(11);
    doc.text('AI INSIGHTS', margin, y);
    y += 6;
    setStroke('#E5E7EB');
    doc.line(margin, y, pageW - margin, y);
    y += 8;

    const insights = [
      {
        type: 'warning',
        text: 'Nutrient level is 30 units below target. Schedule a 7 mL fertilizer dose within the next 6 hours.',
      },
      {
        type: 'good',
        text: 'pH is within optimal range. Maintain current watering pattern.',
      },
      {
        type: 'good',
        text: `Predicted harvest readiness for ${crop}: 4 days. Confidence 87%.`,
      },
    ];
    insights.forEach(({ type, text }) => {
      const fillC = type === 'warning' ? '#FFFBEB' : '#F0FDF4';
      const strokeC = type === 'warning' ? '#FDE68A' : '#DCFCE7';
      const dotC = type === 'warning' ? '#F59E0B' : '#16a34a';
      setFill(fillC);
      setStroke(strokeC);
      const lines = doc.splitTextToSize(text, contentW - 16);
      const h = 8 + lines.length * 5;
      doc.roundedRect(margin, y, contentW, h, 2, 2, 'FD');
      const dc = hex(dotC);
      doc.setFillColor(dc.r, dc.g, dc.b);
      doc.circle(margin + 5, y + 4, 1.5, 'F');
      setColor('#374151');
      doc.setFontSize(9);
      doc.text(lines, margin + 10, y + 5.5);
      y += h + 4;
    });
    y += 4;

    // ── Section: Recommended Actions ─────────────────────
    checkPageBreak(20); // Check if we need new page for this section
    setColor('#16a34a');
    doc.setFontSize(11);
    doc.text('RECOMMENDED ACTIONS', margin, y);
    y += 6;
    setStroke('#E5E7EB');
    doc.line(margin, y, pageW - margin, y);
    y += 8;

    const actions = [
      'Run fertilizer dispenser for 7 mL at 18:00 today.',
      'Reduce LED intensity by 10% during midday peak hours.',
      `Re-test soil pH for ${zoneName} manually in 48 hours.`,
    ];
    actions.forEach((action, i) => {
      checkPageBreak(11); // Check before each action
      setFill('#F9FAFB');
      setStroke('#E5E7EB');
      doc.roundedRect(margin, y, contentW, 9, 2, 2, 'FD');
      setColor('#16a34a');
      doc.setFontSize(9);
      doc.text(`${i + 1}.`, margin + 3, y + 6);
      setColor('#374151');
      doc.text(action, margin + 10, y + 6);
      y += 11;
    });
  }

  // ── Add footer ───────────────────────────────────────────────
  addFooter();

  const filename = `GreenStack-${type === 'ai' ? 'AI-Report' : 'Raw-Report'}-${zoneName.replace(/\s+/g, '-')}.pdf`;
  doc.save(filename);
}

// ─── Component ─────────────────────────────────────────────────────────────────

export function ReportTemplate({
  type,
  onClose,
  zoneName = 'Zone A - Tomatoes',
  crop = 'Tomatoes',
}: Props) {
  const [downloading, setDownloading] = useState(false);
  const isAI = type === 'ai';
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const handleDownload = async () => {
    setDownloading(true);
    // Slight delay so spinner is visible before PDF generation blocks the thread
    await new Promise((r) => setTimeout(r, 80));
    try {
      generatePDF(type, zoneName, crop, today);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white w-full max-w-md rounded-2xl border border-gray-200 shadow-xl my-8 overflow-hidden">
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100 bg-gray-50">
          <div className="flex items-center gap-2">
            {isAI ? (
              <Sparkles className="text-green-600" size={20} />
            ) : (
              <FileText className="text-green-600" size={20} />
            )}
            <span className="text-gray-900">
              {isAI ? 'AI Analyzed Report' : 'Raw Data Report'}
            </span>
          </div>
          <button onClick={onClose} className="p-1 hover:bg-gray-100 rounded-lg transition-colors">
            <X className="text-gray-400" size={20} />
          </button>
        </div>

        <div className="px-5 py-5 space-y-4 max-h-[65vh] overflow-y-auto">
          <div className="bg-gray-50 rounded-xl p-4 border border-gray-200">
            <p className="text-gray-400 text-xs">Generated</p>
            <p className="text-gray-900 text-sm">{today}</p>
            <div className="mt-3 grid grid-cols-2 gap-3">
              <div>
                <p className="text-gray-400 text-xs">Zone</p>
                <p className="text-gray-900 text-sm">{zoneName}</p>
              </div>
              <div>
                <p className="text-gray-400 text-xs">Crop</p>
                <p className="text-gray-900 text-sm">{crop}</p>
              </div>
            </div>
          </div>

          {!isAI ? (
            <>
              <SectionTitle>Sensor Readings (Last 24h)</SectionTitle>
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-gray-400 text-xs border-b border-gray-200">
                    <th className="text-left py-2">Sensor</th>
                    <th className="text-left py-2">Min</th>
                    <th className="text-left py-2">Max</th>
                    <th className="text-left py-2">Avg</th>
                  </tr>
                </thead>
                <tbody className="text-gray-900">
                  <DataRow label="Soil Moisture" min="58%" max="68%" avg="62%" />
                  <DataRow label="Soil pH" min="6.0" max="6.4" avg="6.2" />
                  <DataRow label="Nutrient" min="42" max="58" avg="50" />
                  <DataRow label="Temperature" min="22°C" max="26°C" avg="24°C" />
                </tbody>
              </table>
              <SectionTitle>Hardware Activity Log</SectionTitle>
              <ul className="text-gray-500 text-xs space-y-1.5">
                <li>06:00 — Water pump ON for 12 min</li>
                <li>09:00 — LED lights ON (auto)</li>
                <li>14:30 — Fan triggered, 18 min</li>
                <li>18:00 — Fertilizer dispensed: 5 mL</li>
              </ul>
            </>
          ) : (
            <>
              <div className="bg-green-50 border border-green-200 rounded-xl p-4">
                <div className="flex items-center gap-2 mb-2">
                  <TrendingUp className="text-green-600" size={16} />
                  <span className="text-green-700 text-sm">Health Score</span>
                </div>
                <p className="text-gray-900 text-2xl">82 / 100</p>
                <p className="text-gray-500 text-xs mt-1">
                  +6 vs last week. Trending positive.
                </p>
              </div>

              <SectionTitle>Comparative Analysis</SectionTitle>
              <div className="space-y-2">
                <Bar label="Moisture" current={62} required={70} />
                <Bar label="pH" current={62} required={65} />
                <Bar label="Nutrient" current={50} required={80} />
                <Bar label="Temp" current={24} required={25} />
              </div>

              <SectionTitle>AI Insights</SectionTitle>
              <div className="space-y-2">
                <Insight
                  icon={AlertTriangle}
                  color="text-amber-500"
                  text="Nutrient level is 30 units below target. Schedule a 7 mL fertilizer dose within the next 6 hours."
                />
                <Insight
                  icon={Sparkles}
                  color="text-green-600"
                  text="pH is within optimal range. Maintain current watering pattern."
                />
                <Insight
                  icon={TrendingUp}
                  color="text-green-600"
                  text="Predicted harvest readiness: 4 days. Confidence 87%."
                />
              </div>

              <SectionTitle>Recommended Actions</SectionTitle>
              <ol className="text-gray-500 text-xs space-y-1.5 list-decimal list-inside">
                <li>Run fertilizer dispenser for 7 mL at 18:00.</li>
                <li>Reduce LED intensity by 10% during midday peak.</li>
                <li>Re-test soil pH manually in 48 hours.</li>
              </ol>
            </>
          )}
        </div>

        <div className="px-5 py-4 border-t border-gray-100 bg-gray-50">
          <button
            onClick={handleDownload}
            disabled={downloading}
            className="w-full flex items-center justify-center gap-2 bg-green-600 text-white rounded-xl py-3 hover:bg-green-700 transition-colors shadow-sm disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {downloading ? (
              <>
                <Loader2 size={18} className="animate-spin" />
                <span>Generating PDF…</span>
              </>
            ) : (
              <>
                <Download size={18} />
                <span>Download PDF</span>
              </>
            )}
          </button>
          <p className="text-center text-gray-400 text-[10px] mt-2">
            {isAI ? 'AI Analyzed' : 'Raw Data'} report for {zoneName}
          </p>
        </div>
      </div>
    </div>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <h4 className="text-gray-900 text-sm uppercase tracking-wide mt-2">{children}</h4>
  );
}

function DataRow({ label, min, max, avg }: { label: string; min: string; max: string; avg: string }) {
  return (
    <tr className="border-b border-gray-100">
      <td className="py-2 text-gray-900">{label}</td>
      <td className="py-2 text-gray-400">{min}</td>
      <td className="py-2 text-gray-400">{max}</td>
      <td className="py-2 text-gray-900">{avg}</td>
    </tr>
  );
}

function Bar({ label, current, required }: { label: string; current: number; required: number }) {
  const max = Math.max(current, required, 100);
  return (
    <div>
      <div className="flex justify-between text-xs mb-1">
        <span className="text-gray-700">{label}</span>
        <span className="text-gray-400">
          <span className="text-green-600">{current}</span> / {required}
        </span>
      </div>
      <div className="h-2 bg-gray-100 rounded-full overflow-hidden relative">
        <div
          className="absolute inset-y-0 left-0 bg-green-200 rounded-full"
          style={{ width: `${(required / max) * 100}%` }}
        />
        <div
          className="absolute inset-y-0 left-0 bg-green-500 rounded-full"
          style={{ width: `${(current / max) * 100}%` }}
        />
      </div>
    </div>
  );
}

function Insight({
  icon: Icon,
  color,
  text,
}: {
  icon: React.ElementType;
  color: string;
  text: string;
}) {
  return (
    <div className="flex gap-2 bg-gray-50 border border-gray-100 rounded-lg p-3">
      <Icon className={`${color} flex-shrink-0 mt-0.5`} size={16} />
      <p className="text-gray-500 text-xs">{text}</p>
    </div>
  );
}